---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_facts["distribution"] == "Fedora"

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_facts["distribution"] == "Ubuntu"


- hosts: web_servers
  tags: apache,ubuntu
  become: true
  tasks:  
  - name: install apache on web servers
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
    when: ansible_facts["distribution"] == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package on db servers
    tags: db,fedora
    ansible.builtin.dnf:
      name: mariadb
      state: latest
    when: ansible_facts["distribution"] == "Fedora"
        

