---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_facts["distribution"] == "Fedora"

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_facts["distribution"] == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - geerlingguy.apache

- hosts: db_servers
  become: true
  roles:
    - db_servers
        

